### ISSUE TITLE
We should use estable version tag for docker container

### ISSUE THREAD

**Issue by NITEMAN** [sbitio/trigger-jenkins-job#1]
In order to manage api/signature changes, we should use version tag for gitlab-ci container in https://github.com/sbitio/trigger-jenkins-job/blob/v1.3/action.yaml#L22

Rel https://gitlab.com/sbitio/gitlab-ci/container_registry/1733489

**Comment by KrisMagjistari** [comment]
Done, changed the docker tag from master to v1 of the gitlab-ci container in this PR: https://github.com/sbitio/trigger-jenkins-job/pull/2
